# frozen_string_literal: true

source 'https://rubygems.org'

gem 'jekyll', '~> 4.3'
gem 'just-the-docs', '0.12.0'
gem 'jekyll-redirect-from', '0.16.0'
gem 'jekyll-relative-links', '0.6.1'

group :development do
  gem 'webrick'  # Ruby 3.0+ stdlib removal — needed for `jekyll serve`
end
